const FETCH_AUTH_USER = 'FETCH_AUTH_USER';
const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER';
const UPDATE_AUTH_USER_IMAGE = 'UPDATE_AUTH_USER_IMAGE';

export default {
    FETCH_AUTH_USER,
    UPDATE_AUTH_USER,
    UPDATE_AUTH_USER_IMAGE
};